openapi: 3.0.3
info:
  title: Transferencias - OpenAPI 3.0
  description: Gestionar transferencias
  version: 1.0.11
servers:
  - url: http://localhost:8080
tags:
  - name: Transacciones
    description: Registrar transacciones
  - name: Cuenta
    description: Registrar cuentas
  - name: Cliente
    description: Operations about user
paths:
  /transaccion/deposito:
    post:
      tags:
        - Transacciones
      summary: Registar un depósito
      description: Registrar un deposito
      operationId: regDeposito
      requestBody:
        description: Registrar un nuevo deposito
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
        required: true
      responses:
        '200':
          description: Operación registrad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '422':
          description: Validation exception
  /transaccion/retiro:
    post:
      tags:
        - Transacciones
      summary: Registrar un retiro
      description: Registrar un retiro
      operationId: regRetiro
      requestBody:
        description: Registrar un retiro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /transaccion/transferencia:
    post:
      tags:
        - Transacciones
      summary: Registar una transferencia
      description: Registrar un deposito
      operationId: regTransfer
      requestBody:
        description: Registrar un nuevo deposito
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
        required: true
      responses:
        '200':
          description: Operación registrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '422':
          description: Validation exception
  /transaccion/historial/{ctaId}:
    get:
      tags:
        - Transacciones
      summary: Consultar historial
      description: Consultar Historial
      operationId: historialById
      parameters:
        - name: ctaId
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
  /Cuenta/Registrar:
    post:
      tags:
        - Cuenta
      summary: Registar un depósito
      description: Registrar una cuenta
      operationId: regCuenta
      requestBody:
        description: Registrar una cuenta
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CuentaRequest'
        required: true
      responses:
        '200':
          description: Operación registrad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CuentaResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '422':
          description: Validation exception
  /Cliente/Registrar:
    post:
      tags:
        - Cliente
      summary: Registar un cliente
      description: Registrar un cliente
      operationId: regCliente
      requestBody:
        description: Registrar un cliente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
        required: true
      responses:
        '200':
          description: Operación registrad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '422':
          description: Validation exception
components:
  schemas:
    CuentaRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        ctaId:
          type: integer
          format: int64
          example: 198772
        saldo:
          type: number
          format: int32
          example: 100
    CuentaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        ctaId:
          type: integer
          format: int64
          example: 198772
        saldo:
          type: number
          format: int32
          example: 100
    Cuenta:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        ctaId:
          type: integer
          format: int64
          example: 198772
        saldo:
          type: number
          format: int32
          example: 100

    Cliente:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        nombre:
          type: string
          example: John Doe
    Transfer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        Monto:
          type: number
          example: 100
        fecha:
          type: string
          example: 04/10/2024
        ctaOrigen:
          type: integer
          example: 198772
        ctaDestino:
          type: integer
          example: 198772
  requestBodies:
    Transfer:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transfer'
    Cuenta:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Cuenta'

